# Generated by Django 6.0.3 on 2026-03-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='old_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
