# Generated by Django 6.0.3 on 2026-03-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_book_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_anime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_pack',
            field=models.BooleanField(default=False),
        ),
    ]
