# Generated by Django 6.0.3 on 2026-03-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_is_anime_book_is_best_seller_book_is_new_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_popular',
            new_name='is_kids',
        ),
    ]
