# Generated by Django 6.0.3 on 2026-03-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_payment_method_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='book',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
